version: 2.1
jobs:
  jbrotons:
    docker:
      - image: jant90/jbrotons-ci
    steps:
      - checkout
      - run:
          name: Hello
          command: echo "Hello jbrotons" && ls
workflows:
  jbrotons:
    jobs:
      - jbrotons