version: 2.1
jobs:
  hello:
    docker:
      - image: jant90/jbrotons-ci
    steps:
      - checkout
      - run:
          name: Hello
          command: echo "Hello jbrotons"
workflows:
  hello:
    jobs:
      - hello