version: 2.1
jobs:
  jbrotons:
    docker:
      - image: jant90/jbrotons-ci
    steps:
      - checkout
      - run:
        name: Hello Jbrotons
        command: echo "Hello jbrotons"
workflows:
  jbrotons:
    jobs:
      - jbrotons