version: 2.1
jobs:
  hello:
    docker:
      - image: jant90/jbrotons-ci
    steps:
      - checkout
      run:
        name: Hello World
        command: echo "Hello World"
workflows:
  hello:
    jobs:
      - hello